spring:
  application:
    name: service-registry
server:
  port: ${PORT:8761} # Allows overriding the port with an environment variable in Docker

eureka:
  instance:
    hostname: ${HOSTNAME:service-registry} # Use Docker service name for hostname
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    renewal-percent-threshold: 0.49
