# Path: resources/config/user-service.yml
server:
  port: ${USER_SERVICE_PORT:8082}

spring:
  application:
    name: user-service


security:
  jwt:
    secretKey: ${JWT_SECRET_KEY:supersecretdskjdbbvjkbdvbhaei78che87w7428c87hc4874h847h8c78787}
    expirationTime: 3600000
