spring:
  application:
    name: accounts-service
  config:
    import: "optional:configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8088}" # Fallback to config-server:8088
  profiles:
    active: ${PROFILE:dev} # Default to 'dev' profile

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true
