services:
  agent-name-generator:
    container_name: agent-name-generator
    build: .
    ports:
      - "${AGENT_NAME_GENERATOR_PORT}:${AGENT_NAME_GENERATOR_PORT}"
    environment:
      AGENT_NAME_PORT: ${AGENT_NAME_GENERATOR_PORT}
    networks:
      - microservices

networks:
  microservices:
    external: true
