spring:
  application:
    name: config-server
  profiles:
    active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    preferIpAddress: true

server:
  port: ${CONFIG_PORT:8088}

management:
  endpoints:
    web:
      exposure:
        include: prometheus

