services:
  user-service:
    container_name: user-service
    depends_on:
      - db-user-service
    build: .
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    environment:
      EUREKA_HOST: service-registry
      EUREKA_PORT: ${SERVICE_REGISTRY_PORT}
      CONFIG_HOST: config-server
      CONFIG_PORT: ${CONFIG_SERVER_PORT}
      PROFILE: ${PROFILE}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      DATABASE_HOST: db-user-service
      DATABASE_PORT: ${DB_PORT}
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_SCHEMA: public
    networks:
      - microservices

  db-user-service:
    container_name: db-user-service
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "${DB_PORT}"
    networks:
      - microservices

networks:
  microservices:
    external: true
